skip checking vm.max_map_count

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -115,17 +115,17 @@ jobs:
       - *attach_workspace
       - run: ./.circleci/primary/setup.sh
 
-      - run:
-          name: Check vm.max_map_count for elasticsearch container
-          command: |
-            vm_max_map_count=$(sysctl --values vm.max_map_count)
-            if [ $vm_max_map_count -ge 262144 ]; then
-              exit 0
-            fi
-            >&2 echo "Error: elasticsearch container requires vm.max_map_count >= 262144 but $vm_max_map_count now."
-            >&2 echo "Please execute 'sudo sysctl --write vm.max_map_count=262144' to raise that value on your docker host."
-            >&2 echo "See https://www.elastic.co/guide/en/elasticsearch/reference/5.4/docker.html#docker-cli-run-prod-mode"
-            exit 1
+      # - run:
+      #     name: Check vm.max_map_count for elasticsearch container
+      #     command: |
+      #       vm_max_map_count=$(sysctl --values vm.max_map_count)
+      #       if [ $vm_max_map_count -ge 262144 ]; then
+      #         exit 0
+      #       fi
+      #       >&2 echo "Error: elasticsearch container requires vm.max_map_count >= 262144 but $vm_max_map_count now."
+      #       >&2 echo "Please execute 'sudo sysctl --write vm.max_map_count=262144' to raise that value on your docker host."
+      #       >&2 echo "See https://www.elastic.co/guide/en/elasticsearch/reference/5.4/docker.html#docker-cli-run-prod-mode"
+      #       exit 1
 
       - run:
           command: ./bin/spring server
